#!/usr/bin/env bash
#Transfers a file from our client to a server; accepts 4 parameters
#Before running this script, we will run this to list serve'rs existing content
#       sssh ubuntu@54.236.26.123 -i ~/.ssh/school 'ls ~/'
#       touch newfile.html
# After running script, we will run this to check new content is transferred to server
#       ssh ubuntu@54.236.26.123 -i ~/.ssh/school 'ls ~/'

if [ $# -lt 4 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
    scp -o "StrictHostKeyChecking=no" -i "$4" "$1" "$3@$2":~/
fi
