#!/usr/bin/env bash
# Install nginx on web server; Nginx should be listening on port 80
# Querying Nginx at its root (/) with a GET request (requesting a page)
# 	   curl http://54.236.26.123/   --> returns string "Hello World!"
#	   curl http://54.236.26.123/   --> returns header info

sudo apt-get -y update
sudo apt-get -y install nginx
sudo service nginx start

# allow nging on firewall
sudo ufw allow 'Nginx HTTP'

# Allow user to edit files
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

echo "Hello World!" | sudo tee /usr/share/nginx/html/index.html
